Django 1.8: fix an assertion relating to which template is used
This test was failing because of this error:

  ValueError: assertTemplateUsed() and assertTemplateNotUsed() are only
  usable on responses fetched using the Django test Client.

However, I'm a bit unclear on how this ever worked, since the template
parameter for WriteItDeleteView was never being overridden?